/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aaa_componentes;

import java.awt.Color;
import java.io.Serializable;
import java.time.LocalDate;

/**
 *
 * @author Alejandro
 */
public class NewJPanel extends javax.swing.JFrame implements Serializable  {
    private int mes = LocalDate.now().getMonthValue();
    private int ano = LocalDate.now().getYear();  
    private int m;
    private int a; 
    private int cvc;  
    private JDNIField dni;
    private String dniValidar;
    /**
     * Creates new form NewJPanel1
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDNIField1 = new com.mycompany.aaa_componentes.JDNIField();
        jLabel5 = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        jTFCvc = new javax.swing.JTextField();
        jTFMes = new javax.swing.JTextField();
        jTFAno = new javax.swing.JTextField();
        jTFTargeta = new javax.swing.JTextField();

        jLabel1.setText("Introduzca el numero de la tarjeta: ");

        jLabel2.setText("Fecha de Caducidad: ");

        jLabel3.setText("CVC: ");

        jLabel4.setText("Introduzca el DNI: ");

        jDNIField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setText("/");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        jTFMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFMesFocusLost(evt);
            }
        });

        jTFAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFAnoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnValidar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDNIField1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jTFTargeta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFCvc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFTargeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jTFMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFCvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDNIField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnValidar)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTFMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMesFocusLost
        try {            
            m = Integer.valueOf(jTFMes.getText());
        }catch (Exception e) {
            
        }
    }//GEN-LAST:event_jTFMesFocusLost

    private void jTFAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFAnoFocusLost
        try {            
            this.a = Integer.valueOf(jTFAno.getText());
        }catch (Exception e) {
            
        }
    }//GEN-LAST:event_jTFAnoFocusLost

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        validarFecha();
        validarCVC();        
        dni.validateDNI(dniValidar);
    }//GEN-LAST:event_btnValidarActionPerformed

    public boolean validarFecha() {
        boolean validado = false;
        if (validarAno() && validarMes() ){
            if (ano <= a) {
                if (mes <= m) {
                    validado = true;
                    jTFMes.setForeground(Color.green); 
                    jTFAno.setForeground(Color.green); 
                    
                }
                
                else {
                    jTFMes.setForeground(Color.red);
                    jTFAno.setForeground(Color.red); 
                } 
            }
            else {
                jTFMes.setForeground(Color.red);
                jTFAno.setForeground(Color.red); 
            }
        }
        
            return validado;
    }
    
    private boolean validarMes() {
        boolean mesValido = false;
        
        if(m <= 12) {
            mesValido = true;
        }
        return mesValido;
    }
    
    private boolean validarAno() {
        boolean anoValido = false;
        
        if(a >= 2020 && a < 2050) {
            anoValido = true;
        }
        return anoValido;
    }
    
    public boolean validarCVC() {
        boolean cvcValido = false;
        
        if(cvc > 99 && cvc < 999) {
            cvcValido = true;
        }
        return cvcValido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private com.mycompany.aaa_componentes.JDNIField jDNIField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTFAno;
    private javax.swing.JTextField jTFCvc;
    private javax.swing.JTextField jTFMes;
    private javax.swing.JTextField jTFTargeta;
    // End of variables declaration//GEN-END:variables
}
